name: ⚗️Check

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.21.0"
      - name: build
        run: go build .

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.21.0"
      - name: install goimports
        run: go install golang.org/x/tools/cmd/goimports@${GOIMPORTS_VERSION}
        env:
          GOIMPORTS_VERSION: v0.9.1
      - name: format
        run: goimports -l -w -local .
      - name: check change
        run: |
          git status -s
          test -z "$(git status -s)"
